// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOLLla7sKkBdHYM2CCSPgvNpUeG18OSXY',
    appId: '1:730217989738:web:f5a363346651ea3c07ec13',
    messagingSenderId: '730217989738',
    projectId: 'edywasa-b8473',
    authDomain: 'edywasa-b8473.firebaseapp.com',
    storageBucket: 'edywasa-b8473.appspot.com',
    measurementId: 'G-HZVLHR934H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXzJb_t6lce8XGiAbm8i5hwULrM-XE22w',
    appId: '1:921834200020:android:c7d148970417178a2e1441',
    messagingSenderId: '921834200020',
    projectId: 'teste-staircase',
    storageBucket: 'teste-staircase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqiyR-Kf4535qsglvMKh969wApYjs__8I',
    appId: '1:730217989738:ios:1430f92e4e26f41b07ec13',
    messagingSenderId: '730217989738',
    projectId: 'edywasa-b8473',
    storageBucket: 'edywasa-b8473.appspot.com',
    iosBundleId: 'com.edy.edycliente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqiyR-Kf4535qsglvMKh969wApYjs__8I',
    appId: '1:730217989738:ios:1430f92e4e26f41b07ec13',
    messagingSenderId: '730217989738',
    projectId: 'edywasa-b8473',
    storageBucket: 'edywasa-b8473.appspot.com',
    iosBundleId: 'com.edy.edycliente',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOLLla7sKkBdHYM2CCSPgvNpUeG18OSXY',
    appId: '1:730217989738:web:ee2c86656f69b29107ec13',
    messagingSenderId: '730217989738',
    projectId: 'edywasa-b8473',
    authDomain: 'edywasa-b8473.firebaseapp.com',
    storageBucket: 'edywasa-b8473.appspot.com',
    measurementId: 'G-VJJ6PWKBMS',
  );
}